# version: '3'
# services:

#   api:
#     build: .
#     volumes:
#       - .:/app
#     env_file:
#       - .env
#     restart: on-failure

#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"  # Replace 8080 with the desired port for your application
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Mount your Nginx configuration file
#     depends_on:
#       - api  # Nginx depends on the API service being available

version: '3'
services:
  # Existing services...
  postgres:
    image: postgres:latest
    container_name: devsoc-db
    ports:
      - '5430:5432'
    volumes:
      - postgresDB:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: devsoc-redis
    ports:
      - '6380:6379'
    env_file:
      - .env

  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Replace 8080 with the desired port for your application
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Mount your Nginx configuration file
    depends_on:
      - api  # Nginx depends on the API service being available

volumes:
  postgresDB: