# version: "3" -> Deprecated
services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: on-failure
  postgres:
    image: postgres:latest
    ports:
      - "6500:5432" # cause 5432 is generally used by other postgres servers running
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - .env
  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Replace 8080 with the desired port for your application
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Mount your Nginx configuration file
    depends_on:
      - api # Nginx depends on the API service being available
