version: '3'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
<<<<<<< HEAD
    restart: on-failure
=======
    restart: on-failure
>>>>>>> 726a9f37c180e1133236d65c47932deaa201ba2b
