version: '3'
services:
  api:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    restart: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Replace 8080 with the desired port for your application
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Mount your Nginx configuration file
    depends_on:
      - api  # Nginx depends on the API service being available
