name: Build and Deploy to Server

on:
  push:
    branches:
      - master # Adjust the branch as needed

jobs:
  deploy-to-solar-guardian:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd devsoc-backend-24/
            git pull origin master
            sudo -S docker compose down
            sudo -S docker compose up -d --build

  deploy-to-midnight-sentinel:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST_2 }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD_2 }}
          port: 22
          script: |
            cd devsoc-backend-24/
            git pull origin master
            sudo -S docker compose down
            sudo -S docker compose up -d --build
